### ISSUE TITLE
Some more commands

### ISSUE THREAD

**Issue by quwepiro** [SeptemberHX/joplin-plugin-enhancement#13]
Hi @SeptemberHX   
today I discovered your enhancements plugin and I like it a lot. I uninstalled many other plugins as their functions are also available, and mostly better, in your plugin.

One thing I am missing, and I think that it is not so difficult to implement, is a command for creating tasks.
On my keyboard, the ` [ ] ` and \` characters are not good places and reduce the flow.
So my suggestion is to add the following commands:
 -  `/task` for inserting `- [ ] `
 - `/code` for inserting \`   \` and jumping with the cursor between them
 - `/block` for inserting the following and jumping with the cursor in the free line between.

\`\`\`
  <-- Jump here with cursor
\`\`\`

As I am a Java developer, I unfortunately cannot create a pull request for that, only this issue :)

**Comment by SeptemberHX** [comment]
I am not sure about these commands. They don't seem to save much time:
* `/task`: at least 4 chars
* `/code`: at least 3 chars
* `/block`: at least 2 chars

Instead, I think we can support custom config files so that users can create their own command list. I will try to make it support the configuration file in future.

> As I am a Java developer, I unfortunately cannot create a pull request for that, only this issue :)

Actually, I disagree on that point because I also have no javascript/typescript experience before implementing this plugin 😆. I used to implement small tools in java/python/c++ instead. So I'm sure it won't be too hard to writing something is js/ts.

If you are interested in the commands and want to create PRs, you can check another PR about commands: https://github.com/SeptemberHX/joplin-plugin-enhancement/pull/5

**Comment by SeptemberHX** [comment]
Wow, that's great! I have added the `hacktoberfest` topic and label!

**Comment by SeptemberHX** [comment]
Thanks for the PR!

And yes, I have more ideas. Please refer to #17 and #18. They contain useful links to implement these features.

**Comment by SelectLOL1** [comment]
> 
> Instead, I think we can support custom config files so that users can create their own command list. I will try to make it support the configuration file in future.
>
Hello, thank you all very much for this Plugin! I am having a hard time finding the mentioned config file. How can I access it? Thank you
