### ISSUE TITLE
is it possible don't strike through a checked checkbox item

### ISSUE THREAD

**Issue by tino926** [SeptemberHX/joplin-plugin-enhancement#39]
Is it possible to mark a checkbox as "checked" without striking through the text, like this:
![image](https://github.com/SeptemberHX/joplin-plugin-enhancement/assets/2639399/3e5ccc3f-421b-4062-b351-afd4f39321a1)
The reason is that I still need to read the text, and the "strikethrough" is distracting.

**Comment by vanschnapen** [comment]
I just had the same issue of unreadable todo entries due to the text strike-through.
@tino926 did you try to change the according [line in taskRender.css ](https://github.com/SeptemberHX/joplin-plugin-enhancement/blob/69ddd42bf645feb982d2e1be7d0e33697a61b6ad/src/driver/codemirror/taskAndHeaderRenderer/taskRender.css#L95) to
```
text-decoration: none;
```
?

**Comment by tino926** [comment]
@vanschnapen, Yes this works.
